export const STATUS_CODE_CREATED = 201;
export const STATUS_CODE_CONFLICT = 409;
export const STATUS_CODE_UNAUTHORISED = 406;
export const STATUS_CODE_FORBIDDEN = 403;
export const STATUS_CODE_INVALID = 401;
export const STATUS_CODE_SUCCESS = 200;
